#!/usr/bin/env bash
# Regenerates src/snapshot.ts from the X4BNet VPN CIDR list.
# The snapshot is the cold-start fallback used before KV is seeded.
set -euo pipefail
cd "$(dirname "$0")/.."

URL="https://raw.githubusercontent.com/X4BNet/lists_vpn/main/output/vpn/ipv4.txt"

echo "Fetching $URL"
BODY="$(curl -fsSL "$URL")"
COUNT="$(printf '%s\n' "$BODY" | grep -c . || true)"

{
  echo "// snapshot.ts - GENERATED by tools/update-cidrs.sh - do not edit by hand."
  echo "// Bundled fallback snapshot of the X4BNet VPN CIDR list ($(date -u +%Y-%m-%d))."
  echo "export const VPN_SNAPSHOT ="
  printf '%s\n' "$BODY" | sed 's/"/\\"/g' | sed 's/^/"/; s/$/\\n" +/'
  echo '"";'
} > src/snapshot.ts

echo "Wrote src/snapshot.ts with $COUNT CIDRs."
