source "https://rubygems.org"

# Local preview of the GitHub Pages build:
#   cd docs && bundle install && bundle exec jekyll serve
gem "jekyll", "~> 4.3"
gem "just-the-docs", "~> 0.8"
gem "kramdown-parser-gfm"
